### ISSUE TITLE
191 Replace guest with filter for room types

### ISSUE THREAD

**Issue by mate-joy** [mate-n/tpms#8]
Replace Guest with a filter for the available rooms.

E.g. The user can select “Bungalow BA3” and only availabilities with “Bungalow BA3” appear below.

![Image](https://github.com/mate-n/tpms/assets/106409605/adb0c19a-225e-413e-b331-ac4cd7d21cdf)

AvailabilityService is the service that gets the availabilities.

When the user selects a room, it should send a different query to the backend.

In IProtelAvailabilityPostBody there is a field “roomtype”. Try to fill that in with the room the user has selected.

AvailabilityService → getAvailabilities → 

```
export interface IProtelAvailabilityPostBody {
  arrivaldate: string
  departuredate: string
  roomtype: string | null // <--- this one needs to be filled.
  propertyid: string
  detail: string
  accomodation_type: string | null
}
```

**Comment by phong-hpm** [comment]
```
When the user selects a room
```
Can you please give me api to get all room types for the dropdown?
I can't find api to get all room types, so I do mock data for now:

![Screenshot 2024-07-09 at 17 32 11](https://github.com/mate-n/tpms/assets/45909577/490dbedc-37dc-4951-9a1e-e05b6c8f7cf4)

**Comment by mate-joy** [comment]
Unfortunately, we don’t have a working API for the rooms at the moment.

For now, try to get rooms from the availabilities.

Something like this:

1. User selects camps.
    
2. For every camp, make a a request with `availabilityService.getAvailabilities` and `protelAvailabilityPostBody` (see below)
    
3. Extract `room_type_code` from the availabilities.
    
4. Some parks have the same rooms. In the dropdown, rooms should only appear once. So remove the duplicates.
    

I know it’s not very elegant but we don’t have control over the API.

```
const axios2: AxiosStatic | undefined = inject('axios2')
  const availabilityService = new AvailabilityService(axios2)

  const protelAvailabilityPostBody: IProtelAvailabilityPostBody = {
    arrivaldate: dateFormatter.yyyydashmmdashdd(props.arrivalDate),
    departuredate: dateFormatter.yyyydashmmdashdd(departureDatePlusOne),
    roomtype: 'null',
    propertyid: props.camp.id.toString(),
    detail: '0',
    accomodation_type: null
  }

  availabilityService.getAvailabilities(protelAvailabilityPostBody).then((response) => {
    availabilities.value = response
  })
  
  
  
  export interface IProtelAvailability {
  id: string
  transaction_id: string
  unique_message_id: string
  request_id: string
  date_time: Date
  pms_type: string
  property_code: string
  type: string
  room_type_code: string <-- this is the room for the dropdown.
  default_occupancy: string
  max_occupancy: number
  availability_start: Date
  availability_end: Date
  availability_count: number
  park_name: string
  property_name: string
  room_type_name: string
  features: string
  rates_data: IRatesData[]
}
```

**Comment by mate-joy** [comment]
Maybe, you can omit the propertyid in protelAvailabilityPostBody and get all availabilities at once:

const protelAvailabilityPostBody: IProtelAvailabilityPostBody = {

arrivaldate: dateFormatter.yyyydashmmdashdd(props.arrivalDate),

departuredate: dateFormatter.yyyydashmmdashdd(departureDatePlusOne),

roomtype: 'null',

propertyid: props.camp.id.toString(), // <--- try without this one, or maybe with null or undefined.

detail: '0',

accomodation\_type: null

}

**Comment by mate-joy** [comment]
When I select “Berg en Dal Rest Camp” and “Balule Rest Camp”, “Campsite CK6” appears twice in the drop down. “Campsite CK6” should only appear once.

When I select the first “Campsite CK6”, it seems to update only “Berg en Dal Rest Camp”. It should update all camps.

**Comment by phong-hpm** [comment]
Sorry, I don't understand, I see they are `Campsite CK6P` and `Campsite CK6`, I think 
<img width="389" alt="Screenshot 2024-07-10 at 15 29 04" src="https://github.com/mate-n/tpms/assets/45909577/f9dcdee6-3719-4f3a-905c-e75d20916499">

<img width="381" alt="Screenshot 2024-07-10 at 15 29 16" src="https://github.com/mate-n/tpms/assets/45909577/6dbdb34a-60c5-45e7-af43-fe0dde7c1385">

**Comment by mate-joy** [comment]
Oh, you are right! Apologies, didn’t see that.

**Comment by mate-joy** [comment]
Not urgent:

I’m getting an error on this line:

`roomTypeCodesInDropdown.value = roomTypeCodeSet.values()`

“Type 'IterableIterator<string>' is missing the following properties from type 'string\[\]': length, pop, push, concat, and 27 more.”

I can fix it with:

`roomTypeCodesInDropdown.value = Array.from(roomTypeCodeSet.values())`

Do you have any idea why this happens to me and not to you?

**Comment by mate-joy** [comment]
When I “Berg en Dal Rest Camp” and “Balule Rest Camp” and Room type as “Rhino Guest House GH8B”, then “Campsite CK6” and “Hut EH3” are still visible in “Balule Rest Camp”. Does this happen to you too?
![image](https://github.com/mate-n/tpms/assets/106409605/5db99018-2c92-4585-9609-a44b70f7e1f6)

**Comment by phong-hpm** [comment]
```
When I “Berg en Dal Rest Camp” and “Balule Rest Camp” and Room type as “Rhino Guest House GH8B”, then “Campsite CK6” and “Hut EH3” are still visible in “Balule Rest Camp”. Does this happen to you too?
```

Yes, it happened to me, The reason is api return null item in response:

<img width="390" alt="Screenshot 2024-07-10 at 19 24 10" src="https://github.com/mate-n/tpms/assets/45909577/660b154d-f80e-457c-b447-95c2a85217b5">
